### ISSUE TITLE
XCM failed to get notified due to buy_weight's failure

### ISSUE THREAD

**Issue by Ftais** [parallel-finance/parallel#1183]
**Steps to Reproduce**
1. setting xcmfees is 1pic
2. contribute 1 ksm
3. check balance and check vaults flying data

**Expected vs. Actual Behavior**
XCM send Fail ，User can receive a refund

**Environment**
staing

**Logs, Errors or Screenshots**
![image](https://user-images.githubusercontent.com/20315624/149737311-df884ec9-9c92-43dd-a294-024643740883.png)
![image](https://user-images.githubusercontent.com/20315624/149737351-90a40bf9-fae6-493f-833c-0acb2f4d05a5.png)

**Comment by GopherJ** [comment]
This is polkadot side's issue, since we are unable to pay for `ReportError` etc. xcm-executor will stop while processing the second xcm message - `BuyExecution` since it failed. Then `ReportError` is never executed.

We should do two things:

- ask polkadot to add a new barrier
- add MinimumXcmFees check in xcm-helper
