### ISSUE TITLE
Adjust stake-client to use governance OR multisig OR membership

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1237]

**Comment by MrPai** [comment]
We need to consider this carefully because `settlement` receives two amount as arguments, and it affects a lot on our system.
https://github.com/parallel-finance/parallel/blob/277317d367d70a9814466b5171fb87fcdea99356/pallets/liquid-staking/src/lib.rs#L438-L439

governance OR multisig may be good however it will increase the complexity for stake-client, and if we use membership which means use one node running stake-client, we need seriously consider this node's safety and robust.

**Comment by GopherJ** [comment]
close in favor of #1346
