### ISSUE TITLE
Swap heiko lease to 23/30

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1828]
Refer: https://kusama.subsquare.io/democracy/referendum/199

### Install yq
```
wget https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
```
### Config sudo key
https://github.com/parallel-finance/parallel/blob/master/docs/LAUNCH.md#create-env-file-with-relaychain-sudo-key

**Comment by MrPai** [comment]
## 1 clone code
```
git clone https://github.com/parallel-finance/parallel && cd parallel
```

## 2 generate files
```
parachain-
```

**Comment by MrPai** [comment]
## 3 change lease

**Comment by MrPai** [comment]
# Issue
![image](https://user-images.githubusercontent.com/26266313/181466930-dad29c2a-e1ac-4297-95c9-840ad679299f.png)
![image](https://user-images.githubusercontent.com/26266313/181466971-0f27b02e-f92a-421f-8c46-a25bbc0a42a6.png)
![image](https://user-images.githubusercontent.com/26266313/181466989-0a0cd28c-6e6b-4a53-a374-7d6ae29523c1.png)
![image](https://user-images.githubusercontent.com/26266313/181467009-b49ca75d-569f-4231-9098-2cb14cded2c9.png)

**Comment by MrPai** [comment]
# instruction

**Comment by MrPai** [comment]
we may need to propose another proposal in lease 23
https://kusama.subsquare.io/democracy/proposal/72

**Comment by yz89** [comment]
# Swap Lease For Parallel-Heiko (2085 to 2126)

In the same fashion as [the Shiden swap](https://kusama.subsquare.io/council/motion/476), Parallel requested governance assistance to swap their lease to the new ID (2126). This proposal aims to initiate this change, pending parachain's agreement on their side once the calls are executed.

Parallel-Heiko needing to swap before the LP22 ends (in 7 days) - to do this we aim to execute the following:

1. a forceLease call extending the lease for Parallel-Heiko ID 2085 to LP23;
2. a registrar:swap call (2126, 2085).

The reason behind these two calls, as follows: as long as the leases overlap there should be no downtime on the parachain once the swap happens. The issue is Heiko’s current lease (up until the end of LP22) and the new one (from LP23 to LP30) is they do not overlap: since Heiko’s new bid happened with a new parachain ID, the only way to keep 2085 running is with a swap. The proposal calling forceLease on Heiko gives the chain one more lease period and on the same call swap should enable all the right things to try and avoid downtime.

Proposal hash: 0x24572c5748646b5c1cff86859d93091d00a4be0a60b7d12abfa50479f0b1ec48

Encoded call:
0x1802084700250800000c2017a4f115c013d899b494c955a7ec4cc9786a3997f1823baacc213896a35a00000000000000000000000000000000170000000100000046034e08000025080000

Details call can be found [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/extrinsics/decode/0x1802084700250800000c2017a4f115c013d899b494c955a7ec4cc9786a3997f1823baacc213896a35a00000000000000000000000000000000170000000100000046034e08000025080000)

Preimage is submitted at **TODO**. Please vote at your convenience!

**Comment by MrPai** [comment]
Done:
- https://kusama.subsquare.io/democracy/referendum/219
- https://parallel-heiko.subscan.io/council/174
