### ISSUE TITLE
Prepare live runtime upgrade to 175

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#845]
- [x] Switch part of clients to 1.7.2-rc? and run for 24 hours without errors
- [x] bump spec_version
- [x] bump transaction_version if pallet/extrinsic indexes changed
- [ ] check polkadot's checklist https://github.com/paritytech/polkadot/issues/4095
- [x] do runtime upgrade on testnet https://github.com/parallel-finance/parallel/issues/1057

**Comment by GopherJ** [comment]
blocked by #870

**Comment by GopherJ** [comment]
@yz89 @MrPai this can be urgent to have and the deadline will be in 8 days

**Comment by MrPai** [comment]
Maybe we should test runtime-upgrade based on this #946 
since https://github.com/paritytech/polkadot/releases/tag/v0.9.13 is a HIGH priority.
so we should decide a commit as `version-175` after upgrade v0.9.13 in our code, 
how do you think of this. @yz89 @GopherJ 

runtime upgrade should be totally tested.

**Comment by yz89** [comment]
I hope we update the runtime versions one by one. I prefer to update to 0.9.12 for Heiko this time.
